update 2025-09-21 23:16:32

diff --git a/luci-app-bypass/root/usr/share/bypass/by-switch b/luci-app-bypass/root/usr/share/bypass/by-switch
--- a/luci-app-bypass/root/usr/share/bypass/by-switch
+++ b/luci-app-bypass/root/usr/share/bypass/by-switch
@@ -13,31 +13,35 @@ uci_get_by_type(){
 }
 
 log(){
-	echo "$(date +'%Y-%m-%d %H:%M:%S') By-Switch : $*" >> /tmp/log/$NAME.log
+	echo "$(date +'%Y-%m-%d %H:%M:%S') 自动切换检测： $*" >> /tmp/log/$NAME.log
 }
 
+
 get_ip(){
+	i=0
 	if ! echo $ip | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$">/dev/null;then
 		r=1
-		while ! nslookup $ip 127.0.0.1:5336 >/dev/null 2>&1;do
+		while ! nslookup $ip >/dev/null 2>&1;do
 			[ $r -ge 10 ] && return 1 || let r++
 			sleep 1
 		done
-		ip=$(nslookup $ip 127.0.0.1:5336 2>/dev/null | grep Address | awk -F' ' '{print$NF}' | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$");i=$?
+		ip=$(nslookup $ip 2>/dev/null | grep Address | awk -F' ' '{print$NF}' | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$");i=$?
 		ip=$(echo "$ip" | sed -n 1p)
 	fi
 	return $i
 }
 
 f_bin(){
+	w=
 	case $1 in
 		ss)w=$(which ss-local);;
 		ssr)w=$(which ssr-local);;
 		v2ray)w=$(which xray)||w=$(which r2ray);;
+		hysteria2)w=$(which hysteria);;
 		trojan)w=$(which trojan-plus);;
 		naiveproxy)w=$(which naive);;
 	esac
-	echo ${w:=0}
+	echo $w
 }
 
 gen_port(){
@@ -64,8 +68,8 @@ gen_config_file(){
 "fast_open":$fast
 }
 EOF
-			plugin=$(uci_get_by_name $1 plugin 0)
-			if [ $plugin != 0 -a -x "$(which $plugin)" ];then
+			plugin=$(uci_get_by_name $1 plugin)
+			if [ $plugin ];then
 				sed -i "s@$ip\",@$ip\",\n\"plugin\":\"$plugin\",\n\"plugin_opts\":\"$(uci_get_by_name $1 plugin_opts)\",@" $J
 			fi;;
 		ssr)
@@ -96,6 +100,7 @@ EOF
 }
 EOF
 ;;
+
 	esac
 }
 
@@ -105,25 +110,32 @@ curl_check(){
 	fi
 	type=$(uci_get_by_name $1 type)
 	if [ $type = tun ];then
-		curl --interface $(uci_get_by_name $1 iface br-lan) --resolve dns.google:443:8.8.8.8 -so /dev/null --connect-timeout 20 https://dns.google;return $?
+		curl --interface $(uci_get_by_name $1 iface br-lan) --resolve www.google.com:443:216.239.38.120 -so /dev/null --connect-timeout 20 https://www.google.com;i=$?
+		[ $i = 0 ] || log "Server : $($UCI$1.alias || uci_get_by_name $1 server) cURL check error, Try to switch another server."
+		return $i
 	elif [ $type != socks5 ];then
 		cmd=$(f_bin $type)
-		if [ ! -x $cmd ];then
+		if [ ! $cmd ];then
 			[ $type = ss -o $type = ssr ] && type=$type-local
 			log "Can't find $(echo $type) program, Skip this Node($($UCI$1.alias || uci_get_by_name $1 server))."
 			return 1
 		fi
 	fi
 	gen_port
-	J=/var/etc/$NAME/by-socks5-check.json
+	J=/var/etc/$NAME-check.json
 	gen_config_file $1
 	IP=127.0.0.1
 	param=
 	case $type in
 		ss|ssr)
 			$cmd -c $J >/dev/null 2>&1 &;;
-		v2ray|hysteria)
-			$S/gen_config $1 tcp 0 $lport $ip > $J
+		v2ray)
+			$S/gen_xray $1 tcp 0 $lport $ip > $J
+			sed -i 's/\\//g' $J
+			$cmd run -config $J  >/dev/null 2>&1 &
+			;;
+		hysteria2)
+			$S/gen_hysteria2 $1 tcp 0 $lport $ip >$J
 			sed -i 's/\\//g' $J
 			$cmd -c $J >/dev/null 2>&1 &;;
 		trojan)
@@ -147,8 +159,8 @@ curl_check(){
 		[ $r -ge 10 ] && return 1 || let r++
 		sleep 1
 	done
-	curl -x socks5://$IP:$lport $param --resolve dns.google:443:8.8.8.8 -so /dev/null --connect-timeout 20 https://dns.google;i=$?
-	kill -9 $(ps -w | grep $J | grep -v grep | awk '{print$1}') 2>/dev/null
+	curl -x socks5://$IP:$lport $param --resolve www.google.com:443:216.239.38.120 -so /dev/null --connect-timeout 20 https://www.google.com;i=$?
+	kill -9 $(busybox ps -w | grep -v grep | grep $J  | awk '{print$1}') 2>/dev/null
 	rm -f $J
 	[ $i = 0 ] || log "Server : $($UCI$1.alias || uci_get_by_name $1 server) cURL check error, Try to switch another server."
 	return $i
@@ -172,8 +184,10 @@ test_proxy(){
 
 check_proxy(){
 	for i in $(seq 1 $(uci_get_by_type global switch_try_count 3));do
-		curl -so /dev/null --connect-timeout $time_b https://www.google.com && return 0
-		curl -so /dev/null --connect-timeout $time_b https://www.baidu.com && a=1 || a=2
+		curl --connect-timeout $time_b -so /dev/null https://www.google.com/generate_204 && return 0
+		a=2
+		ping -c 3 -W 1 223.5.5.5 > /dev/null 2>&1
+		[ $? -eq 0 ] &&	a=1
 		sleep 1
 	done
 	return $a
@@ -191,58 +205,68 @@ select_proxy(){
 		get_ip || continue
 		port=$(uci_get_by_name $d server_port)
 		ipset add ss_spec_wan_ac $ip 2>/dev/null
-		x=$?
-		$S/by-check $ip $port $time_b && curl_check $d
-		y=$?
-		[ $x = 0 ] && ipset del ss_spec_wan_ac $ip 2>/dev/null
-		if [ $y = 0 ];then
+		$S/by-check $ip $port $time_b
+		local ret=$?
+		ipset del ss_spec_wan_ac $ip 2>/dev/null
+		if [ "$ret" == "0" ]; then
 			SERVER_C=$d
 			c=$i
 			return 0
 		fi
+
 	done
 }
 
 switch_proxy(){
-	/etc/init.d/$NAME restart $SERVER_B
+	/etc/init.d/$NAME restart $1
+	return 0
 }
 
 [ "$1" = start ] || exit 1
 SERVER_A=$(uci_get_by_type global global_server)
 SERVER_B=$SERVER_A
-[ $(uci_get_by_name $SERVER_A kcp_enable 0) = 1 ] && exit 1
+
+SERVER_C=0
+[ $(uci_get_by_name $SERVER_A kcp_enable 0) = 1 ] && return 1
 c=1
 time_a=$(uci_get_by_type global switch_time 300)
 time_b=$(uci_get_by_type global switch_timeout 5)
 UCI="uci -q get $NAME."
 sleep 10
 while :;do
-	if [ $SERVER_A != $SERVER_B ];then
-		log "Current server : $($UCI$SERVER_B.alias || uci_get_by_name $SERVER_B server) is not main server, Try to switch back to $($UCI$SERVER_A.alias || uci_get_by_name $SERVER_A server)."
-		if test_proxy $SERVER_A;then
-			log "Main server is available. Switch to main server."
-			SERVER_B=$SERVER_A
-			switch_proxy
-			continue
-		else
-			log "Main server is not available. Continue using current server."
-		fi
-	fi
+	#检测主节点是否能使用
 	check_proxy
-	a=$?
-	if [ $a = 1 ];then
-		log "Current server : $($UCI$SERVER_B.alias || uci_get_by_name $SERVER_B server) error.Try to switch another server."
+	status=$?
+	if [ "$status" == 2 ]; then
+		log "无法连接到网络，请检查网络是否正常！"
+		return 2
+	fi
+
+	if [ $SERVER_A != $SERVER_B ];then
+		test_proxy $SERVER_A
+		[ $? -eq 0 ] && {
+			#主节点正常，切换到主节点
+			log "${SERVER_A}主节点【$($UCI$SERVER_A.alias || uci_get_by_name $SERVER_A server)】正常，切换到主节点！"
+			SERVER_B=$SERVER_A
+			switch_proxy $SERVER_B
+			[ $? -eq 0 ] && {
+				log "【$($UCI$SERVER_B.alias || uci_get_by_name $SERVER_B server)】节点切换完毕！"
+			}
+			return 0
+		}
+	fi
+		
+	if [ "$status" == 0 ]; then
+		return 0
+	elif [ "$status" == "1" ]; then
+	
+		log "【$($UCI$SERVER_B.alias || uci_get_by_name $SERVER_B server) 】异常，切换到下一个节点！"
 		select_proxy
 		if [ $SERVER_C != 0 ];then
-			log "Another server : $($UCI$SERVER_C.alias || uci_get_by_name $SERVER_C server) is available.Now switching server."
 			SERVER_B=$SERVER_C
-			switch_proxy
-		else
-			log "No server available. Try restart current server."
-			switch_proxy
+			log "$($UCI$SERVER_B.alias || uci_get_by_name $SERVER_B server) 正常，切换到此节点！"
+			switch_proxy  $SERVER_B
 		fi
-	elif [ $a = 2 ];then
-		log "Network Problem. Do nothing."
 	fi
 	sleep $time_a
 done
